# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newsAPI_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newsAPI_practice
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'newsAPI_practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'newsAPI_practiceUITests' do
    # Pods for testing
  end

end
